services:
  - type: web
    name: task-vault-backend
    env: python
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task-vault-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        value: your-django-secret-key
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: task-vault-backend.onrender.com,task-vault-frontend.onrender.com

  - type: web
    name: task-vault-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: serve -s dist   # 👈 change to `build` if CRA
    buildFilter:
      paths: ["frontend/**"]
    staticPublishPath: dist       # 👈 or `build` if CRA
    envVars:
      - key: REACT_APP_API_URL
        value: https://task-vault-backend.onrender.com/api
